# from https://hub.docker.com/_/caddy/
caddy_home: "{{docker_project_root}}/caddy"
caddy_tasks: true

caddy_capabilities:
  - NET_ADMIN

caddy_ports:
  - "80:80"
  - "443:443"
  - "443:443/udp"

# note that caddy_config is not the "config" folder, but the
# conf folder that the Caddyfile and certs can be put in

caddy_caddyfile_template: caddy_Caddyfile.j2
caddy_conf: "{{caddy_home}}/conf"
caddy_caddyfile: "{{caddy_conf}}/Caddyfile"
caddy_srv: "{{caddy_home}}/srv"

# set this to mount the specified directory into /etc/ssl/private
caddy_certs: null

# A list of jinja templates to copy to the srv folder
caddy_srv_templates: []
