caddy_home: "{{docker_project_root}}/caddy"
caddy_tasks: true

caddy_capabilities:
  - NET_ADMIN
caddy_ports:
  - "80:80"
  - "443:443"
  - "443:443/udp"

caddy_caddyfile_template: caddy_Caddyfile.j2
caddy_caddyfile: "{{caddy_home}}/Caddyfile"
caddy_srv: "{{caddy_home}}/srv"
caddy_data: "{{caddy_home}}/data"
caddy_config: "{{caddy_home}}/config"
