# from https://hub.docker.com/_/caddy/
docker_caddy_home: "{{docker_project_root}}/caddy"
docker_caddy_tasks: true

docker_caddy_capabilities:
  - NET_ADMIN

docker_caddy_ports:
  - "80:80"
  - "443:443"
  - "443:443/udp"

# note that docker_caddy_config is not the "config" folder, but the
# conf folder that the Caddyfile and certs can be put in

docker_caddy_caddyfile_template: caddy_Caddyfile.j2
docker_caddy_conf: "{{docker_caddy_home}}/conf"
docker_caddy_caddyfile: "{{docker_caddy_conf}}/Caddyfile"
docker_caddy_srv: "{{docker_caddy_home}}/srv"

# set this to mount the specified directory into /etc/ssl/private
docker_caddy_certs: null

# A list of jinja templates to copy to the srv folder
docker_caddy_srv_templates: []

docker_caddy_restart_policy: "always"
