docker_gluetun_tasks: true
docker_gluetun_home: "{{docker_project_root}}/gluetun"
docker_gluetun_data: "{{docker_gluetun_home}}/data"

# See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
docker_gluetun_vpn: null

# e.g.
# - "OPENVPN_USER=abc"
# - "OPENVPN_PASSWORD=abc"
# OR
# - "WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
docker_gluetun_credentials: null

docker_gluetun_vpn_type: openvpn

docker_gluetun_ports:
  - "8888:8888/tcp # HTTP proxy"
  - "8388:8388/tcp # Shadowsocks"
  - "8388:8388/udp # Shadowsocks"

docker_gluetun_updater_period: 72h

# example list of countries
docker_gluetun_server_countries:
  - United States
  - Germany
  - France
  - Ireland
  - United Kingdom
  - Canada
  - Australia
  - Japan

docker_gluetun_shared_network: null
