docker_jackett_tasks: true
docker_jackett_home: "{{docker_project_root}}/jackett"

# set this if you want jackett to be in the same docker network
# as something else
docker_jackett_shared_network: null

# user/group to run as
docker_jackett_uuid: 65534
docker_jackett_guid: 65534

docker_jackett_ports:
  - "9117:9117"
