time_zone: "Etc/UTC"
docker_user: root
docker_project_root: "/opt/docker-projects"
docker_containers: []

# from https://straz.to/2021-09-08-docker-address-pools/
docker_daemon_config:
  default-address-pools:
    - base: "172.17.0.0/12"
      size: 20
    - base: "192.168.0.0/16"
      size: 24
