docker_ollama_tasks: false
docker_ollama_image: ollama/ollama:latest
docker_ollama_restart_policy: unless-stopped

docker_ollama_ports:
  - "127.0.0.1:11434:11434"

docker_ollama_environment:
  OLLAMA_HOST: "0.0.0.0:11434"
  OLLAMA_NUM_PARALLEL: "1"
  OLLAMA_MAX_LOADED_MODELS: "1"
  OLLAMA_KEEP_ALIVE: "10m"
