docker_qbittorrent_tasks: true
docker_qbittorrent_image: lscr.io/linuxserver/qbittorrent:latest
docker_qbittorrent_home: "{{docker_project_root}}/qbittorrent"

docker_qbittorrent_ports:
  - "8080:8080"
  - "6881:6881"
  - "6881:6881/udp"

docker_qbittorrent_downloads: "{{docker_qbittorrent_home}}/downloads"
docker_qbittorrent_config: "{{docker_qbittorrent_home}}/config"

# use this to have the container share network namespace with another
docker_qbittorrent_network_mode: null

# user/group to run as
docker_qbittorrent_uuid: 1000
docker_qbittorrent_guid: 1000

# want to be careful about restarting this in case it needs a proxy
docker_qbittorrent_restart_policy: "no"
