docker_squid_tasks: true
docker_squid_conf_template: squid_squid.conf.j2
docker_squid_home: "{{docker_project_root}}/squid"

# set this if you want the port to be forwarded
docker_squid_ports:
  - "3128:3128"

# set this if you want this to be in the same docker network
# as something else
docker_squid_shared_network: null

# use this to have the container share network namespace with another
docker_squid_upstream_container: null

docker_squid_proxy_user: proxy
