- name: Add Docker GPG Key
  become: true
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0644'
    force: true

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main
    state: present

- name: Update apt and install alloy
  become: true
  apt:
    name: alloy
    state: latest
    update_cache: true
