- name: Ensure apt keyrings directory exists
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG Key
  become: true
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0644'
    force: true

- name: Add Docker Repository
  become: true
  ansible.builtin.copy:
    content: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
    dest: /etc/apt/sources.list.d/grafana.list
    mode: '0644'

- name: Update apt and install alloy
  become: true
  apt:
    name: alloy
    state: latest
    update_cache: true
