- name: OS Installation details
  debug:
      msg: >
        Installing grafana alloy for {{ansible_os_family}}
        / {{ansible_distribution}}
        / {{ansible_distribution_release}}
        / {{ansible_distribution_version}}

- name: Install grafana alloy
  include_tasks:
    file: install_{{ansible_os_family|lower}}.yml

- name: Write api key to file
  tags: grafanaconfig
  ansible.builtin.copy:
    content: "{{ grafana_alloy_basic_auth_password }}"
    dest: "/etc/alloy/api.password"
    owner: "{{grafana_alloy_user}}"
    mode: 0600
  become: true
  when: grafana_alloy_basic_auth_password is not none

- name: Write alloy config
  tags: grafanaconfig
  ansible.builtin.template:
    src: "{{ grafana_alloy_config_template }}"
    dest: "/etc/alloy/config.alloy"
    owner: "{{grafana_alloy_user}}"
    mode: '640'
  become: true

- name: Enable alloy service, and restart to pick up changes
  ansible.builtin.systemd_service:
    name: alloy
    state: restarted
    enabled: yes
  become: true
