- hosts: all
  roles:
    - { role: base, tags: base }
    - { role: packages, tags: packages }
    - { role: users, tags: users }

- hosts: docker_hosts
  roles:
    - { role: docker, tags: docker }
