- hosts: all
  roles:
    - { role: base, tags: base }
    - { role: packages, tags: packages, when: "'packages_hosts' not in group_names" }
    - { role: users, tags: users }

- hosts: packages_hosts
  roles:
    - { role: packages, tags: packages }

- hosts: docker_hosts
  roles:
    - { role: docker, tags: docker }

- hosts: lxc_hosts
  roles:
    - { role: lxc, tags: lxc }

- hosts: grafana_hosts
  roles:
    - { role: grafana, tags: grafana }
