- name: Create caddy web root directory
  ansible.builtin.file:
    path: "{{ packages_caddy_srv }}"
    state: directory
    owner: "{{ packages_caddy_user }}"
    group: "{{ packages_caddy_group }}"
    mode: '755'
  become: true

- name: Set caddyfile
  ansible.builtin.template:
    src: "{{packages_caddy_caddyfile_template}}"
    dest: "{{packages_caddy_config}}"
    owner: "{{packages_caddy_user}}"
    group: "{{packages_caddy_group}}"
    mode: '440'
    validate: 'caddy validate --config %s --adapter caddyfile'
  become: true

- name: Copy caddy web data
  ansible.builtin.template:
    src: "{{ packages_caddy_item }}"
    dest: "{{ packages_caddy_srv }}/{{ packages_caddy_item | basename | regex_replace('\\.j2$', '') }}"
    owner: "{{ packages_caddy_user }}"
    group: "{{ packages_caddy_group }}"
    mode: '444'
  loop: "{{ packages_caddy_srv_templates }}"
  loop_control:
    loop_var: packages_caddy_item
  become: true
