- name: Checking OS
  debug:
    msg: OS Family is {{ ansible_os_family }}

- name: Update package cache
  ansible.builtin.yum: update_cache=yes
  when: ansible_os_family == "RedHat"
  become: true

- name: Update package cache
  ansible.builtin.apt: update_cache=yes
  when: ansible_os_family == "Debian"
  become: true

- name: Ensure a list of packages installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  become: true
  loop: "{{required_packages + required_packages_group + required_packages_host}}"

- name: Run any per-package task sets
  tags: packageupdate
  block:
  - include_tasks:
      file: "{{item}}_tasks.yml"
    when: lookup('vars', item + '_tasks', default=false)
    loop: "{{required_packages + required_packages_group + required_packages_host}}"

- name: All done!
  debug:
    msg: Packages have been successfully installed
