- name: tinyproxy config management
  debug:
    msg:
    - "{{ packages_tinyproxy_config }}"
    - "{{ ansible_facts['default_ipv4']['network'] | default('unknown') }}"
    - "{{ ansible_facts['default_ipv4']['prefix'] | default('unknown') }}"

- name: Update tinyproxy config
  ansible.builtin.lineinfile:
    path: "{{ packages_tinyproxy_config }}"
    state: present
    line: "{{ packages_tinyproxy_item }}"
  loop: "{{ packages_tinyproxy_required_lines }}"
  loop_control:
    loop_var: packages_tinyproxy_item
  become: true
