- name: tinyproxy config management
  debug:
    msg:
    - "{{ tinyproxy_config }}"
    - "{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['network'] }}"
    - "{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['prefix'] }}"

- name: Update tinyproxy config
  ansible.builtin.lineinfile:
    path: "{{ tinyproxy_config }}"
    state: present
    line: "{{ tinyproxy_item }}"
  loop: "{{ tinyproxy_required_lines }}"
  loop_control:
    loop_var: tinyproxy_item
  become: true
