- name: tinyproxy config management
  debug:
    msg:
    - "{{ packages_tinyproxy_config }}"
    - "{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['network'] }}"
    - "{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['prefix'] }}"

- name: Update tinyproxy config
  ansible.builtin.lineinfile:
    path: "{{ packages_tinyproxy_config }}"
    state: present
    line: "{{ packages_tinyproxy_item }}"
  loop: "{{ packages_tinyproxy_required_lines }}"
  loop_control:
    loop_var: packages_tinyproxy_item
  become: true
