- name: Set fact for Debian
  set_fact:
    sudo_group: "sudo"
  when: ansible_os_family == "Debian"

- name: Set fact for RedHat
  set_fact:
    sudo_group: "wheel"
  when: ansible_os_family == "RedHat"

- name: Add main user with sudo permissions
  ansible.builtin.user:
    name: "{{ main_user }}"
    comment: "{{ main_user }}"
    shell: "{{ main_user_shell }}"
    group: '{{sudo_group}}'
  become: true

- name: Set authorized key taken from file for main user
  ansible.posix.authorized_key:
    user: "{{ main_user }}"
    state: present
    key: "{{ main_user_public_key }}"
  become: true

- name: Add automation user
  ansible.builtin.user:
    name: "{{ automation_user }}"
    comment: "{{ automation_user }}"
    shell: "{{ automation_user_shell }}"
    password_lock: yes
    password: "*"
  become: true
  tags: automation_user

- name: Set authorized key taken from file for automation user
  ansible.posix.authorized_key:
    user: "{{ automation_user }}"
    state: present
    key: "{{ automation_user_public_key }}"
  become: true
  tags: automation_user

- name: Copy automation sudoers file
  ansible.builtin.template:
    src: automation_sudoers.j2
    dest: /etc/sudoers.d/automation_sudoers
    owner: root
    group: root
    mode: '400'
  tags: automation_user
  become: true

- name: Copy automation automation_scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /root/automation/scripts/
    owner: root
    group: root
    mode: '500'
  loop: "{{ automation_scripts + automation_scripts_host }}"
  become: true
  tags: automation_user
