docker_portainer_tasks: false
docker_portainer_ports:
  - "127.0.0.1:9443:9443" # HTTPS UI
# - "127.0.0.1:9000:9000" # HTTP UI
# - "127.0.0.1:8000:8000" # Edge compute features

docker_portainer_shared_network: null
