- name: Create data directories
  file:
    path: "{{compose_softether_item}}"
    state: directory
    mode: '0700'
    owner: "{{compose_user}}"
    group: "{{compose_user}}"
  become: true
  loop:
    - "{{compose_softether_home}}/data"
    - "{{compose_softether_home}}/log"
    - "{{compose_softether_home}}/packetlog"
    - "{{compose_softether_home}}/securitylog"
  loop_control:
    loop_var: compose_softether_item
