- name: Create caddy conf directory
  file:
    path: "{{docker_caddy_conf}}"
    state: directory
    mode: '0700'
    owner: "{{docker_user}}"
    group: "{{docker_user}}"
  become: true

- name: Create caddy srv directory
  file:
    path: "{{docker_caddy_srv}}"
    state: directory
    mode: '0700'
    owner: "{{docker_user}}"
    group: "{{docker_user}}"
  become: true

- name: Set caddyfile
  debug:
    msg: "{{docker_caddy_caddyfile}}"

- name: Set caddyfile
  ansible.builtin.template:
    src: "{{docker_caddy_caddyfile_template}}"
    dest: "{{docker_caddy_caddyfile}}"
    owner: "{{docker_user}}"
    group: "{{docker_user}}"
    mode: '600'
  become: true

- name: Copy caddy web data
  ansible.builtin.template:
    src: "{{ docker_caddy_item }}"
    dest: "{{docker_caddy_srv}}/{{ docker_caddy_item | basename | regex_replace('\\.j2$', '') }}"
    owner: "{{docker_user}}"
    group: "{{docker_user}}"
    mode: '444'
  loop: "{{ docker_caddy_srv_templates }}"
  loop_control:
    loop_var: docker_caddy_item
  become: true
