- name: Create caddy config directory
  file:
    path: "{{caddy_config}}"
    state: directory
    mode: '0700'
    owner: "{{docker_user}}"
    group: "{{docker_user}}"
  become: true

- name: Create caddy srv directory
  file:
    path: "{{caddy_srv}}"
    state: directory
    mode: '0700'
    owner: "{{docker_user}}"
    group: "{{docker_user}}"
  become: true

- name: Create caddy data directory
  file:
    path: "{{caddy_data}}"
    state: directory
    mode: '0700'
    owner: "{{docker_user}}"
    group: "{{docker_user}}"
  become: true

- name: Set caddyfile
  debug:
    msg: "{{caddy_caddyfile}}"

- name: Set caddyfile
  ansible.builtin.template:
    src: "{{caddy_caddyfile_template}}"
    dest: "{{caddy_caddyfile}}"
    owner: "{{docker_user}}"
    group: "{{docker_user}}"
    mode: '600'
  become: true

- name: Copy caddy web data
  ansible.builtin.template:
    src: "{{ caddy_item }}"
    dest: "{{caddy_srv}}/{{ caddy_item | basename | regex_replace('\\.j2$', '') }}"
    owner: "{{docker_user}}"
    group: "{{docker_user}}"
    mode: '444'
  loop: "{{ caddy_srv_templates }}"
  loop_control:
    loop_var: caddy_item
  become: true
