- name: Find duplicate Docker apt source files
  become: true
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d
    patterns:
      - '*.list'
      - '*.sources'
    contains: 'download\.docker\.com'
    read_whole_file: true
  register: docker_apt_source_files
  when: ansible_facts['os_family'] == "Debian"

- name: Remove duplicate Docker apt source files
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ docker_apt_source_files.files | default([]) }}"
  when:
    - ansible_facts['os_family'] == "Debian"
    - item.path != '/etc/apt/sources.list.d/docker.list'
