- name: Create get_iplayer config directory
  file:
    path: "{{docker_get_iplayer_config}}"
    state: directory
    mode: '0700'
    owner: "{{docker_get_iplayer_uuid}}"
    group: "{{docker_get_iplayer_guid}}"
  become: true

- name: Create get_iplayer downloads directory
  file:
    path: "{{docker_get_iplayer_downloads}}"
    state: directory
    mode: '0700'
    owner: "{{docker_get_iplayer_uuid}}"
    group: "{{docker_get_iplayer_guid}}"
  become: true
