- name: Add Docker GPG Key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add Docker Repository
  become: true
  ansible.builtin.copy:
    content: "deb [signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] | lower }} stable"
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'

- name: Update apt and install docker-ce
  become: true
  apt:
    name: docker-ce
    state: latest
    update_cache: true
