- name: Add Docker GPG Key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} stable
    state: present

- name: Update apt and install docker-ce
  become: true
  apt:
    name: docker-ce
    state: latest
    update_cache: true
