# install docker
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true


- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true

- name: Update package cache
  ansible.builtin.yum: update_cache=yes
  when: ansible_os_family == "RedHat"
  become: true

- name: Update package cache
  ansible.builtin.apt: update_cache=yes
  when: ansible_os_family == "Debian"
  become: true


- name: Ensure a list of packages installed
  ansible.builtin.package:
    name: docker-ce
    state: latest
  become: true
