- name: Create data directories
  file:
    path: "{{softether_item}}"
    state: directory
    mode: '0700'
    owner: "{{docker_user}}"
    group: "{{docker_user}}"
  become: true
  loop:
    - "{{softether_home}}/data"
    - "{{softether_home}}/log"
    - "{{softether_home}}/packetlog"
    - "{{softether_home}}/securitylog"
  loop_control:
    loop_var: softether_item
