- name: Set squid.conf
  ansible.builtin.template:
    src: "{{squid_conf_template}}"
    dest: "{{squid_home}}/squid.conf"
    owner: "{{squid_proxy_user}}"
    group: "{{squid_proxy_user}}"
    mode: '600'
  become: true
